name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test 01
      id: test-01
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test 01
        setup-command: pip3 install pandas
        command: python3 tests.py 01
        timeout: 10
        max-score: 1
    - name: Test 02
      id: test-02
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test 02
        setup-command: pip3 install pandas
        command: python3 tests.py 02
        timeout: 10
        max-score: 1
    - name: Test 03
      id: test-03
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test 03
        setup-command: pip3 install pandas
        command: python3 tests.py 03
        timeout: 10
        max-score: 1
    - name: Test 04
      id: test-04
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test 04
        setup-command: pip3 install pandas
        command: python3 tests.py 04
        timeout: 10
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-01_RESULTS: "${{steps.test-01.outputs.result}}"
        TEST-02_RESULTS: "${{steps.test-02.outputs.result}}"
        TEST-03_RESULTS: "${{steps.test-03.outputs.result}}"
        TEST-04_RESULTS: "${{steps.test-04.outputs.result}}"
      with:
        runners: test-01,test-02,test-03,test-04
